spring:
  application:
    name: springcloud-consumer
server:
  port: 8010
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@172.21.10.184:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}

#ribbon.eureka.enabled: false  ##Use Ribbon Without Eureka
#springcloud-provider.ribbon.listOfServers: 172.21.10.184:7903
#springcloud-provider-ribbon-random.ribbon.listOfServers: 172.21.10.184:7901 

 